kind: pipeline
name: nodb

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: nodb-php8.0
  image: nextcloudci/php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
services:
- name: cache
  image: redis

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: sqlite

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: sqlite-php8.0
  image: nextcloudci/php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
services:
- name: cache
  image: redis

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
